// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://caelpearderjwnpkgjst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhZWxwZWFyZGVyanducGtnanN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM3NjgyMTMsImV4cCI6MjA0OTM0NDIxM30.PIBvm2YwjlVPFO89zc60V4qy_OJDL8cVtochiMvWFac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);